# Migrate the database when something is pushed to main/test
name: Migrate

on:
  push:
    branches:
      - main
      - test

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    
    env:
      PRISMA_FIELD_ENCRYPTION_KEY: ${{ secrets.PRISMA_FIELD_ENCRYPTION_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: yarn install --frozen-lockfile --silent

      - name: Generate
        run: yarn generate

      - name: Run migrations
        run: yarn prisma migrate deploy --preview-feature

      - name: Seed store data
        run: yarn store:update

